#pragma once

//SPI Pins
#define SPI_SCK_PIN GP18
#define SPI_MOSI_PIN GP19
#define SPI_MISO_PIN GP16

//TFT Config
#define TFT_RESET_PIN GP20
#define TFT_CS_PIN GP17
#define TFT_DC_PIN GP21
#define TFT_WIDTH 128
#define TFT_HEIGHT 160
#define TFT_ROTATION QP_ROTATION_180

#define QUANTUM_PAINTER_SUPPORTS_NATIVE_COLORS TRUE
#define QUANTUM_PAINTER_DISPLAY_TIMEOUT 1800000
#define QP_LVGL_TASK_PERIOD 100

//Switch Pins defined as DipSwitch
#define DIP_SWITCH_PINS { GP15, GP28 }

#define WS2812_DI_PIN GP14
#define RGBLIGHT_LED_COUNT 41
#define RGBLIGHT_LAYERS
#define RGBLIGHT_LAYER_BLINK

//Encoder Config
#define ENCODER_A_PINS { GP26 }
#define ENCODER_B_PINS { GP27 }
#define ENCODER_RESOLUTION 4
