// Copyright 2024 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics --input A:/Code/qmk_firmware/keyboards/handwired/mmooffhand/frog_open.gif --output A:/Code/qmk_firmware/keyboards/handwired/mmooffhand/display/images --format rgb565 --no-rle False --no-deltas False`

#pragma once

#include <qp.h>

extern const uint32_t gfx_frog_open_length;
extern const uint8_t  gfx_frog_open[5924];
