// Copyright 2024 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics --input C:/Users/billg/Documents/GitHub/qmk_firmware/keyboards/handwired/mmooffhand/frog.gif --output C:/Users/billg/Documents/GitHub/qmk_firmware/keyboards/handwired/mmooffhand/display/images --format rgb565 --no-rle False --no-deltas False`

#pragma once

#include <qp.h>

extern const uint32_t gfx_frog_length;
extern const uint8_t  gfx_frog[2861];
